# INTRO

[[exercises]]
name = "intro1"
path = "exercises/intro/intro1.rs"
mode = "compile"
hint = """
Remove the I AM NOT DONE comment to move on to the next exercise."""

# DESIGN PATTERNS

[[exercises]]
name = "design pattern1"
path = "exercises/design-pattern/use-borrowed-types-for-arguments.rs"
mode = "compile"
hint = """
No hint. Good luck!"""
