# INTRO

[[exercises]]
name = "intro1"
path = "exercises/intro/intro1.rs"
mode = "compile"
hint = """
Remove the I AM NOT DONE comment to move on to the next exercise."""

# DESIGN PATTERNS

[[exercises]]
name = "design_pattern1"
path = "exercises/design_patterns/design_pattern1.rs"
mode = "compile"
hint = """
Use borrowed types for arguments.
https://rust-unofficial.github.io/patterns/idioms/coercion-arguments.html"""
